version: 2

models:
  - name: areas
    columns:
      - name: area_id
        tests:
          - unique
          - not_null

  - name: competitions
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: area_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('areas')
                field: area_id
